export enum AvatarFigurePartType {
    BODY = 'bd',
    SHOES = 'sh',
    LEGS = 'lg',
    CHEST = 'ch',
    WAIST_ACCESSORY = 'wa',
    CHEST_ACCESSORY = 'ca',
    HEAD = 'hd',
    HAIR = 'hr',
    FACE_ACCESSORY = 'fa',
    EYE_ACCESSORY = 'ea',
    HEAD_ACCESSORY = 'ha',
    HEAD_ACCESSORY_EXTRA = 'he',
    COAT_CHEST = 'cc',
    CHEST_PRINT = 'cp',
    LEFT_HAND_ITEM = 'li',
    LEFT_HAND = 'lh',
    LEFT_SLEEVE = 'ls',
    RIGHT_HAND = 'rh',
    RIGHT_SLEEVE = 'rs',
    FACE = 'fc',
    EYES = 'ey',
    HAIR_BIG = 'hrb',
    RIGHT_HAND_ITEM = 'ri',
    LEFT_COAT_SLEEVE = 'lc',
    RIGHT_COAT_SLEEVE = 'rc',
}
